Fix path spaces

diff --git a/root/etc/s6-overlay/s6-rc.d/svc-mod-qbittorrent-freezetag/run b/root/etc/s6-overlay/s6-rc.d/svc-mod-qbittorrent-freezetag/run
--- a/root/etc/s6-overlay/s6-rc.d/svc-mod-qbittorrent-freezetag/run
+++ b/root/etc/s6-overlay/s6-rc.d/svc-mod-qbittorrent-freezetag/run
@@ -6,10 +6,10 @@ CATEGORY="${FTAG_DL_CATEGORY}"
 CATEGORY_FZ="${FTAG_FZ_CATEGORY:-${CATEGORY}_frozen}"
 
 log() {
-    echo "[mod-freezetag] INFO:${1}" >&2
+    echo "[mod-freezetag] INFO: ${1}" >&2
 }
 log_error() {
-    echo "[mod-freezetag] ERROR:${1}" >&2
+    echo "[mod-freezetag] ERROR: ${1}" >&2
 }
 log_debug() {
     if [ "${DOCKER_MODS_DEBUG,,}" = 'true' ]; then
